### ISSUE TITLE
Support for --source and --target in JavaBuild::compile()

### ISSUE THREAD

**Issue by tmpfs** [project-robius/android-build#1]
Hi,

I am trying to compile your excellent `robius-authentication` crate for android using a Flutter/Android Studio setup and I am getting a class version mismatch.

I ***think*** it is because in the Android Studio gradle config I have:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
```

But when `JavaBuild::compile()` is executed it uses the latest available version (21) yielding this error:

```
SEVERE:   Error in /Users/muji/git/sos/local_auth/build/rust_lib_local_auth/build/aarch64-linux-android/debug/build/robius-authentication-3a6eb04dd668c228/out/robius/authentication/AuthenticationCallback.class:
SEVERE:   java.lang.IllegalArgumentException: Unsupported class file major version 65
```

I really don't want to change the version in Android Studio as it will likely wreak havoc with other dependencies so I wonder if it makes sense to add a couple more environment variables to `android-build` so we can specify the source and target compile versions?

Perhaps `ANDROID_SOURCE_VERSION` and `ANDROID_TARGET_VERSION` could be translated to the `--source` and `--target` javac options?

I don't think it's feasible to set `JavaBuild::command()` directly as `android-build` is a transient dependency of `robius-authentication` in this case.

FWIW, these are the configured environment variables (trying to ensure that `android-build` uses the same JDK as Android Studio):

```
export ANDROID_JAR="$ANDROID_SDK/platforms/android-34/android.jar"
export ANDROID_SDK_ROOT="$ANDROID_SDK"
export ANDROID_D8_JAR="$ANDROID_SDK/build-tools/34.0.0/lib/d8.jar"
export ANDROID_BUILD_TOOLS_VERSION="34.0.0"
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
```

Happy to contribute a PR if you think this approach is correct, thanks 🙏

**Comment by tmpfs** [comment]
A note to myself or anyone else stumbling on this, after updating to set `--source` and `--target` in a fork I hit this error:

```
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':app:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/muji/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/jlink with arguments {--module-path /Users/muji/.gradle/caches/8.10.2/transforms/7e6fe1d7056aecdc23d8f8d7c1f001d4-d1961ba1-ee63-44c4-8320-d1c77b9c65c5/transformed/output/temp/jmod --add-modules java.base --output /Users/muji/.gradle/caches/8.10.2/transforms/7e6fe1d7056aecdc23d8f8d7c1f001d4-d1961ba1-ee63-44c4-8320-d1c77b9c65c5/transformed/output/jdkImage --disable-plugin system-modules}
```

The fix was to update the "com.android.application" (in my case from `8.1.0`to `8.7.0`) to:

```
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "8.7.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}
```

And make sure you are using `8.10.2` in the gradle wrapper.

Edit: To remind me, also fixed the "context not initialized error" using these docs: https://cjycode.com/flutter_rust_bridge/guides/how-to/ndk-init.

**Comment by kevinaboos** [comment]
thanks, this is certainly something we'd be happy to add support for. 

(sorry for the delay, was on vacation)

**Comment by tmpfs** [comment]
All good @kevinaboos , hope you had a good vacation! I have updated the PR which should close this 👍
